version: '3.8'

services:
  # PostgreSQL - Основная база данных
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: main_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: main_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - db-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  # MongoDB - Хранение ордеров и финансовой статистики
  mongo-db:
    image: mongo:6.0
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - db-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  # ClickHouse - Аналитика действий с ордерами
  clickhouse-db:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse-db
    ports:
      - "8123:8123"  # HTTP интерфейс ClickHouse
      - "9000:9000"  # TCP интерфейс ClickHouse
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    networks:
      - db-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  # Java-приложение
  finance-app:
    image: openjdk:21-jdk
    container_name: finance-app
    volumes:
      - ./target:/app
    working_dir: /app
    command: ["java", "-jar", "finance-and-investment.jar"]
    ports:
      - "8080:8080"
    networks:
      - db-network
    depends_on:
      - postgres-db
      - mongo-db
      - clickhouse-db

networks:
  db-network:
    driver: bridge

volumes:
  postgres-data:
  mongo-data:
  clickhouse-data:
